### ISSUE TITLE
The krunker hack doesnt even work

### ISSUE THREAD

**Issue by AlphaIceBreaker** [TEAMOVERSONIC/hack-bundle-tampermonkey#1]
dude ur just copying other peoples scripts but it doesnt even work.

**Comment by TEAMOVERSONIC** [comment]
i will update it now

**Comment by TEAMOVERSONIC** [comment]
and plus in the read me it said warning i am collecting other peoples script and using them

**Comment by TEAMOVERSONIC** [comment]
read the README.MD dushbag

**Comment by TEAMOVERSONIC** [comment]
read the comment at the top of the krunker hack it clearly states what to do

**Comment by AlphaIceBreaker** [comment]
what do i do? i just copied it and pasted it into a tampermonkey script? can you help me please

**Comment by AlphaIceBreaker** [comment]
?
