### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by IceHacks** [TEAMOVERSONIC/hack-bundle-tampermonkey#13]
![image](https://user-images.githubusercontent.com/38994479/74781525-b3252b00-5245-11ea-936f-98b0c3dbbe07.png)

I wonder what this one is for... 😁

Thx for adding my cheat btw.

**Comment by TEAMOVERSONIC** [comment]
Your Welcome

**Comment by TEAMOVERSONIC** [comment]
Btw Thats Just Something Random That I Added It Doesn't work
